; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Dev\LevOS\kernel\GFXApp\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?OUT@@YAXD@Z					; OUT
; Function compile flags: /Odtp /ZI
; File c:\dev\levos\kernel\gfxapp\main.cpp
;	COMDAT ?OUT@@YAXD@Z
_TEXT	SEGMENT
_a$ = 8							; size = 1
?OUT@@YAXD@Z PROC					; OUT, COMDAT

; 12   : 	{

	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi

; 13   : 			_asm mov dx, 0xE9

	mov	dx, 233					; 000000e9H

; 14   : 			_asm mov al, a

	mov	al, BYTE PTR _a$[ebp]

; 15   : 			_asm out dx, al

	out	dx, al

; 16   : 	}

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?OUT@@YAXD@Z ENDP					; OUT
_TEXT	ENDS
PUBLIC	??_C@_09KKBHBBKF@LevOS?52?40?$AA@		; `string'
PUBLIC	??_C@_0BM@KGEMJOIP@Levex?5is?5an?5epic?5developer?$CB?$AA@ ; `string'
PUBLIC	??_C@_08OBGPNNFO@test?4bmp?$AA@			; `string'
PUBLIC	??_C@_0N@BPJMLEOO@?6Gfx?5init?4?4?4?$AA@	; `string'
PUBLIC	_main
EXTRN	?VGA_deinit@@YAXXZ:PROC				; VGA_deinit
EXTRN	?VGA_putchar@@YAXHHD@Z:PROC			; VGA_putchar
EXTRN	?repaintScreen@@YAXXZ:PROC			; repaintScreen
EXTRN	?getWindowById@@YAPAUWINDOW@@D@Z:PROC		; getWindowById
EXTRN	?addWindow@@YAHUWINDOW@@@Z:PROC			; addWindow
EXTRN	?W_TEXTPOPUP_init@@YAXPAUW_TEXTPOPUP@@PAUWINDOW@@PAD2@Z:PROC ; W_TEXTPOPUP_init
EXTRN	?VGA_clear@@YAXXZ:PROC				; VGA_clear
EXTRN	?VGA_putimage@@YAXHHPAD@Z:PROC			; VGA_putimage
EXTRN	?VGA_init@@YAXXZ:PROC				; VGA_init
EXTRN	?getInputChar@@YADXZ:PROC			; getInputChar
EXTRN	?print@@YAXPAD@Z:PROC				; print
;	COMDAT ??_C@_09KKBHBBKF@LevOS?52?40?$AA@
CONST	SEGMENT
??_C@_09KKBHBBKF@LevOS?52?40?$AA@ DB 'LevOS 2.0', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@KGEMJOIP@Levex?5is?5an?5epic?5developer?$CB?$AA@
CONST	SEGMENT
??_C@_0BM@KGEMJOIP@Levex?5is?5an?5epic?5developer?$CB?$AA@ DB 'Levex is a'
	DB	'n epic developer!', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_08OBGPNNFO@test?4bmp?$AA@
CONST	SEGMENT
??_C@_08OBGPNNFO@test?4bmp?$AA@ DB 'test.bmp', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@BPJMLEOO@?6Gfx?5init?4?4?4?$AA@
CONST	SEGMENT
??_C@_0N@BPJMLEOO@?6Gfx?5init?4?4?4?$AA@ DB 0aH, 'Gfx init...', 00H ; `string'
; Function compile flags: /Odtp /ZI
CONST	ENDS
;	COMDAT _main
_TEXT	SEGMENT
_w$ = -76						; size = 34
_tp$ = -40						; size = 8
_timeout$ = -32						; size = 4
_my$ = -28						; size = 4
_mx$ = -24						; size = 4
_y$ = -12						; size = 4
_x$ = -8						; size = 4
_c$ = -1						; size = 1
_main	PROC						; COMDAT

; 21   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 144				; 00000090H
	push	ebx
	push	esi
	push	edi

; 22   : 	print("\nGfx init...");

	push	OFFSET ??_C@_0N@BPJMLEOO@?6Gfx?5init?4?4?4?$AA@
	call	?print@@YAXPAD@Z			; print
	add	esp, 4
$LN11@main:

; 23   : 	while(getInputChar() == 0);

	call	?getInputChar@@YADXZ			; getInputChar
	movsx	eax, al
	test	eax, eax
	jne	SHORT $LN10@main
	jmp	SHORT $LN11@main
$LN10@main:

; 24   : 	VGA_init();

	call	?VGA_init@@YAXXZ			; VGA_init

; 25   : 	VGA_putimage(16, 16, "test.bmp");

	push	OFFSET ??_C@_08OBGPNNFO@test?4bmp?$AA@
	push	16					; 00000010H
	push	16					; 00000010H
	call	?VGA_putimage@@YAXHHPAD@Z		; VGA_putimage
	add	esp, 12					; 0000000cH
$LN9@main:

; 26   : 	while(getInputChar() == 0);

	call	?getInputChar@@YADXZ			; getInputChar
	movsx	eax, al
	test	eax, eax
	jne	SHORT $LN8@main
	jmp	SHORT $LN9@main
$LN8@main:

; 27   : 	VGA_clear();

	call	?VGA_clear@@YAXXZ			; VGA_clear

; 28   : 	//VGA_putstring(16, 160, "string printing WORKING");
; 29   : 	char c = 0;

	mov	BYTE PTR _c$[ebp], 0

; 30   : 	int x = 0, y = 0;

	mov	DWORD PTR _x$[ebp], 0
	mov	DWORD PTR _y$[ebp], 0

; 31   : 	//VGA_putrect(16, 16, 250, 450);
; 32   : 	MOUSE_STATE m;
; 33   : 	int mx = 0; int my = 0;

	mov	DWORD PTR _mx$[ebp], 0
	mov	DWORD PTR _my$[ebp], 0

; 34   : 	int timeout = 100000;

	mov	DWORD PTR _timeout$[ebp], 100000	; 000186a0H

; 35   : 	W_TEXTPOPUP tp;
; 36   : 	WINDOW w;
; 37   : 	W_TEXTPOPUP_init(&tp, &w, "LevOS 2.0" ,"Levex is an epic developer!");

	push	OFFSET ??_C@_0BM@KGEMJOIP@Levex?5is?5an?5epic?5developer?$CB?$AA@
	push	OFFSET ??_C@_09KKBHBBKF@LevOS?52?40?$AA@
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	lea	ecx, DWORD PTR _tp$[ebp]
	push	ecx
	call	?W_TEXTPOPUP_init@@YAXPAUW_TEXTPOPUP@@PAUWINDOW@@PAD2@Z ; W_TEXTPOPUP_init
	add	esp, 16					; 00000010H

; 38   : 	//w.title = "Levex Popup";
; 39   : 	w.move(&w, 120, 120);

	push	120					; 00000078H
	push	120					; 00000078H
	lea	eax, DWORD PTR _w$[ebp]
	push	eax
	call	DWORD PTR _w$[ebp+4]
	add	esp, 12					; 0000000cH

; 40   : 
; 41   : 	addWindow(w);

	sub	esp, 36					; 00000024H
	mov	ecx, 8
	lea	esi, DWORD PTR _w$[ebp]
	mov	edi, esp
	rep movsd
	movsw
	call	?addWindow@@YAHUWINDOW@@@Z		; addWindow
	add	esp, 36					; 00000024H

; 42   : 	WINDOW* wp;
; 43   : 	w = *getWindowById(w.windowId);

	movzx	eax, BYTE PTR _w$[ebp+29]
	push	eax
	call	?getWindowById@@YAPAUWINDOW@@D@Z	; getWindowById
	add	esp, 4
	mov	ecx, 8
	mov	esi, eax
	lea	edi, DWORD PTR _w$[ebp]
	rep movsd
	movsw
$LN7@main:

; 44   : 
; 45   : 	while(true)

	mov	eax, 1
	test	eax, eax
	je	SHORT $LN6@main

; 46   : 	{
; 47   : 		repaintScreen();

	call	?repaintScreen@@YAXXZ			; repaintScreen

; 48   : 		c = getInputChar();

	call	?getInputChar@@YADXZ			; getInputChar
	mov	BYTE PTR _c$[ebp], al

; 49   : 		if(c == 0) continue;

	movsx	eax, BYTE PTR _c$[ebp]
	test	eax, eax
	jne	SHORT $LN5@main
	jmp	SHORT $LN7@main
$LN5@main:

; 50   : 		VGA_putchar(x += 8, y, c);

	mov	eax, DWORD PTR _x$[ebp]
	add	eax, 8
	mov	DWORD PTR _x$[ebp], eax
	movzx	ecx, BYTE PTR _c$[ebp]
	push	ecx
	mov	edx, DWORD PTR _y$[ebp]
	push	edx
	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	call	?VGA_putchar@@YAXHHD@Z			; VGA_putchar
	add	esp, 12					; 0000000cH

; 51   : 		//printHexa(c);
; 52   : 		//if(c == 0xD){ y += 8; x = 0; continue; }
; 53   : 		if(c == 0x64) {  w.move(&w, w.startX + 16, w.startY);  continue; } // d

	movsx	eax, BYTE PTR _c$[ebp]
	cmp	eax, 100				; 00000064H
	jne	SHORT $LN4@main
	mov	eax, DWORD PTR _w$[ebp+17]
	push	eax
	mov	ecx, DWORD PTR _w$[ebp+13]
	add	ecx, 16					; 00000010H
	push	ecx
	lea	edx, DWORD PTR _w$[ebp]
	push	edx
	call	DWORD PTR _w$[ebp+4]
	add	esp, 12					; 0000000cH
	jmp	SHORT $LN7@main
$LN4@main:

; 54   : 		if(c == 0x61) { /*wp->move(wp, wp->startX - 16,  wp->startY);*/ continue; } // a

	movsx	eax, BYTE PTR _c$[ebp]
	cmp	eax, 97					; 00000061H
	jne	SHORT $LN3@main
	jmp	SHORT $LN7@main
$LN3@main:

; 55   : 		if(c == 0x77) { /*wp->move(wp, wp->startX,wp->startY - 16); */continue; } // w

	movsx	eax, BYTE PTR _c$[ebp]
	cmp	eax, 119				; 00000077H
	jne	SHORT $LN2@main
	jmp	SHORT $LN7@main
$LN2@main:

; 56   : 		if(c == 0x73) {/* wp->move(wp, wp->startX,wp->startY + 16); */continue; } // s

	movsx	eax, BYTE PTR _c$[ebp]
	cmp	eax, 115				; 00000073H
	jne	SHORT $LN1@main
	jmp	SHORT $LN7@main
$LN1@main:

; 57   : 		/*if(c == 0x08) //bksp
; 58   : 		{
; 59   : 			x -= 8;
; 60   : 			VGA_putchar(x, y, ' ');
; 61   : 			continue;
; 62   : 		}
; 63   : 		VGA_putchar(x, y, c);
; 64   : 		x += 8;*/
; 65   : 	}

	jmp	$LN7@main
$LN6@main:

; 66   : 	//getInputChar();
; 67   : 	VGA_deinit();

	call	?VGA_deinit@@YAXXZ			; VGA_deinit

; 68   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
