; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Dev\LevOS\kernel\GFXApp\TextPopup.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?OUTc@@YAXD@Z					; OUTc
; Function compile flags: /Odtp /ZI
; File c:\dev\levos\kernel\gfxapp\textpopup.cpp
;	COMDAT ?OUTc@@YAXD@Z
_TEXT	SEGMENT
_a$ = 8							; size = 1
?OUTc@@YAXD@Z PROC					; OUTc, COMDAT

; 6    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi

; 7    : 		_asm mov dx, 0xE9

	mov	dx, 233					; 000000e9H

; 8    : 		_asm mov al, a

	mov	al, BYTE PTR _a$[ebp]

; 9    : 		_asm out dx, al

	out	dx, al

; 10   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?OUTc@@YAXD@Z ENDP					; OUTc
_TEXT	ENDS
PUBLIC	?W_TEXTPOPUP_paint@@YAXPAUWINDOW@@@Z		; W_TEXTPOPUP_paint
EXTRN	__imp__VGA_putstring:PROC
EXTRN	__imp__VGA_putrect:PROC
EXTRN	__imp__VGA_setcolor:PROC
EXTRN	__imp__VGA_getcolor:PROC
; Function compile flags: /Odtp /ZI
;	COMDAT ?W_TEXTPOPUP_paint@@YAXPAUWINDOW@@@Z
_TEXT	SEGMENT
_c$ = -1						; size = 1
_w$ = 8							; size = 4
?W_TEXTPOPUP_paint@@YAXPAUWINDOW@@@Z PROC		; W_TEXTPOPUP_paint, COMDAT

; 13   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi

; 14   : 	char c = VGA_getcolor();

	call	DWORD PTR __imp__VGA_getcolor
	mov	BYTE PTR _c$[ebp], al

; 15   : 	VGA_setcolor(1);

	push	1
	call	DWORD PTR __imp__VGA_setcolor
	add	esp, 4

; 16   : 	/* WINDOW PRIMITIVE */
; 17   : 	VGA_putrect(w->startX, w->startY, w->endX, w->startY + 12);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+17]
	add	ecx, 12					; 0000000cH
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+21]
	push	eax
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [ecx+17]
	push	edx
	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+13]
	push	ecx
	call	DWORD PTR __imp__VGA_putrect
	add	esp, 16					; 00000010H

; 18   : 	VGA_putstring(w->startX + 2 , w->startY + 2, w->title);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+30]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+17]
	add	eax, 2
	push	eax
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [ecx+13]
	add	edx, 2
	push	edx
	call	DWORD PTR __imp__VGA_putstring
	add	esp, 12					; 0000000cH

; 19   : 	VGA_putrect(w->startX, w->startY, w->endX, w->endY);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+25]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+21]
	push	eax
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [ecx+17]
	push	edx
	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+13]
	push	ecx
	call	DWORD PTR __imp__VGA_putrect
	add	esp, 16					; 00000010H

; 20   : 	/* END WINDOW PRIMITIVE */
; 21   : 	VGA_putstring(w->startX + 2, (w->startY + w->endY) / 2, ((W_TEXTPOPUP*)(w->bigBro))->text);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [eax+17]
	mov	ecx, DWORD PTR _w$[ebp]
	add	eax, DWORD PTR [ecx+25]
	cdq
	sub	eax, edx
	sar	eax, 1
	push	eax
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+13]
	add	eax, 2
	push	eax
	call	DWORD PTR __imp__VGA_putstring
	add	esp, 12					; 0000000cH

; 22   : 	VGA_setcolor(c);

	movzx	eax, BYTE PTR _c$[ebp]
	push	eax
	call	DWORD PTR __imp__VGA_setcolor
	add	esp, 4

; 23   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?W_TEXTPOPUP_paint@@YAXPAUWINDOW@@@Z ENDP		; W_TEXTPOPUP_paint
_TEXT	ENDS
PUBLIC	?W_TEXTPOPUP_move@@YAXPAUWINDOW@@HH@Z		; W_TEXTPOPUP_move
; Function compile flags: /Odtp /ZI
;	COMDAT ?W_TEXTPOPUP_move@@YAXPAUWINDOW@@HH@Z
_TEXT	SEGMENT
_c$ = -9						; size = 1
_height$ = -8						; size = 4
_width$ = -4						; size = 4
_w$ = 8							; size = 4
_x$ = 12						; size = 4
_y$ = 16						; size = 4
?W_TEXTPOPUP_move@@YAXPAUWINDOW@@HH@Z PROC		; W_TEXTPOPUP_move, COMDAT

; 26   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 76					; 0000004cH
	push	ebx
	push	esi
	push	edi

; 27   : 	/* save me */
; 28   : 	//OUTc('C');
; 29   : 	int width = w->endX - w->startX;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [eax+21]
	sub	edx, DWORD PTR [ecx+13]
	mov	DWORD PTR _width$[ebp], edx

; 30   : 	int height = w->endY - w->startY;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [eax+25]
	sub	edx, DWORD PTR [ecx+17]
	mov	DWORD PTR _height$[ebp], edx

; 31   : 	/* clear me */
; 32   : 
; 33   : 	char c = VGA_getcolor();

	call	DWORD PTR __imp__VGA_getcolor
	mov	BYTE PTR _c$[ebp], al

; 34   : 	VGA_setcolor(0);

	push	0
	call	DWORD PTR __imp__VGA_setcolor
	add	esp, 4

; 35   : 	VGA_putrect(w->startX, w->startY, w->endX, w->startY + 12);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+17]
	add	ecx, 12					; 0000000cH
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+21]
	push	eax
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [ecx+17]
	push	edx
	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+13]
	push	ecx
	call	DWORD PTR __imp__VGA_putrect
	add	esp, 16					; 00000010H

; 36   : 	VGA_putstring(w->startX + 2 , w->startY + 2, w->title);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+30]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+17]
	add	eax, 2
	push	eax
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [ecx+13]
	add	edx, 2
	push	edx
	call	DWORD PTR __imp__VGA_putstring
	add	esp, 12					; 0000000cH

; 37   : 	VGA_putrect(w->startX, w->startY, w->endX, w->endY);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+25]
	push	ecx
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+21]
	push	eax
	mov	ecx, DWORD PTR _w$[ebp]
	mov	edx, DWORD PTR [ecx+17]
	push	edx
	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+13]
	push	ecx
	call	DWORD PTR __imp__VGA_putrect
	add	esp, 16					; 00000010H

; 38   : 	/* END WINDOW PRIMITIVE */
; 39   : 	VGA_putstring(w->startX + 2, (w->startY + w->endY) / 2, ((W_TEXTPOPUP*)(w->bigBro))->text);

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [eax+17]
	mov	ecx, DWORD PTR _w$[ebp]
	add	eax, DWORD PTR [ecx+25]
	cdq
	sub	eax, edx
	sar	eax, 1
	push	eax
	mov	edx, DWORD PTR _w$[ebp]
	mov	eax, DWORD PTR [edx+13]
	add	eax, 2
	push	eax
	call	DWORD PTR __imp__VGA_putstring
	add	esp, 12					; 0000000cH

; 40   : 
; 41   : 	/* redraw move */
; 42   : 	w->startX = x;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _x$[ebp]
	mov	DWORD PTR [eax+13], ecx

; 43   : 	w->startY = y;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _y$[ebp]
	mov	DWORD PTR [eax+17], ecx

; 44   : 	w->endX = w->startX + width;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+13]
	add	ecx, DWORD PTR _width$[ebp]
	mov	edx, DWORD PTR _w$[ebp]
	mov	DWORD PTR [edx+21], ecx

; 45   : 	w->endY = w->startY + height;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+17]
	add	ecx, DWORD PTR _height$[ebp]
	mov	edx, DWORD PTR _w$[ebp]
	mov	DWORD PTR [edx+25], ecx

; 46   : 	return;
; 47   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?W_TEXTPOPUP_move@@YAXPAUWINDOW@@HH@Z ENDP		; W_TEXTPOPUP_move
_TEXT	ENDS
PUBLIC	?W_TEXTPOPUP_init@@YAXPAUW_TEXTPOPUP@@PAUWINDOW@@PAD2@Z ; W_TEXTPOPUP_init
EXTRN	?strlen@@YAIPBD@Z:PROC				; strlen
; Function compile flags: /Odtp /ZI
;	COMDAT ?W_TEXTPOPUP_init@@YAXPAUW_TEXTPOPUP@@PAUWINDOW@@PAD2@Z
_TEXT	SEGMENT
_t$ = 8							; size = 4
_w$ = 12						; size = 4
_title$ = 16						; size = 4
_str$ = 20						; size = 4
?W_TEXTPOPUP_init@@YAXPAUW_TEXTPOPUP@@PAUWINDOW@@PAD2@Z PROC ; W_TEXTPOPUP_init, COMDAT

; 50   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi

; 51   : 	t->text = str;

	mov	eax, DWORD PTR _t$[ebp]
	mov	ecx, DWORD PTR _str$[ebp]
	mov	DWORD PTR [eax], ecx

; 52   : 	w->startX = 45;

	mov	eax, DWORD PTR _w$[ebp]
	mov	DWORD PTR [eax+13], 45			; 0000002dH

; 53   : 	w->startY = 45;

	mov	eax, DWORD PTR _w$[ebp]
	mov	DWORD PTR [eax+17], 45			; 0000002dH

; 54   : 	w->endX = w->startX + (strlen(t->text) + 1)*8;

	mov	eax, DWORD PTR _t$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	?strlen@@YAIPBD@Z			; strlen
	add	esp, 4
	mov	edx, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [edx+13]
	lea	edx, DWORD PTR [ecx+eax*8+8]
	mov	eax, DWORD PTR _w$[ebp]
	mov	DWORD PTR [eax+21], edx

; 55   : 	w->endY = w->startY + 45;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR [eax+17]
	add	ecx, 45					; 0000002dH
	mov	edx, DWORD PTR _w$[ebp]
	mov	DWORD PTR [edx+25], ecx

; 56   : 	w->isValid = true;

	mov	eax, DWORD PTR _w$[ebp]
	mov	BYTE PTR [eax+12], 1

; 57   : 	w->title = title;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _title$[ebp]
	mov	DWORD PTR [eax+30], ecx

; 58   : 	w->paint = (void(__cdecl*)(void*))W_TEXTPOPUP_paint;

	mov	eax, DWORD PTR _w$[ebp]
	mov	DWORD PTR [eax], OFFSET ?W_TEXTPOPUP_paint@@YAXPAUWINDOW@@@Z ; W_TEXTPOPUP_paint

; 59   : 	w->move = (void(__cdecl*)(void*, int, int))W_TEXTPOPUP_move;

	mov	eax, DWORD PTR _w$[ebp]
	mov	DWORD PTR [eax+4], OFFSET ?W_TEXTPOPUP_move@@YAXPAUWINDOW@@HH@Z ; W_TEXTPOPUP_move

; 60   : 	w->bigBro = t;

	mov	eax, DWORD PTR _w$[ebp]
	mov	ecx, DWORD PTR _t$[ebp]
	mov	DWORD PTR [eax+8], ecx

; 61   : 	t->window = w;

	mov	eax, DWORD PTR _t$[ebp]
	mov	ecx, DWORD PTR _w$[ebp]
	mov	DWORD PTR [eax+4], ecx

; 62   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?W_TEXTPOPUP_init@@YAXPAUW_TEXTPOPUP@@PAUWINDOW@@PAD2@Z ENDP ; W_TEXTPOPUP_init
_TEXT	ENDS
END
