; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Dev\LevOS\kernel\Kernel\GUFL.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_BSS	SEGMENT
_loaderList DB	090H DUP (?)
_BSS	ENDS
PUBLIC	?GUFL_init@@YA_NXZ				; GUFL_init
; Function compile flags: /Ogtpy
; File c:\dev\levos\kernel\kernel\gufl.cpp
;	COMDAT ?GUFL_init@@YA_NXZ
_TEXT	SEGMENT
?GUFL_init@@YA_NXZ PROC					; GUFL_init, COMDAT

; 9    : 	for(int i = 0; i < GUFL_MAX_NUMBER_OF_LOADERS; i++)

	mov	eax, OFFSET _loaderList
	xor	ecx, ecx
$LL3@GUFL_init:

; 10   : 	{
; 11   : 		loaderList[i].valid = false;

	mov	BYTE PTR [eax+8], cl

; 12   : 		loaderList[i].load = 0;

	mov	DWORD PTR [eax], ecx

; 13   : 		loaderList[i].verify = 0;

	mov	DWORD PTR [eax+4], ecx
	add	eax, 9
	cmp	eax, OFFSET _loaderList+144
	jl	SHORT $LL3@GUFL_init

; 14   : 	}
; 15   : 	return true;

	mov	al, 1

; 16   : }

	ret	0
?GUFL_init@@YA_NXZ ENDP					; GUFL_init
_TEXT	ENDS
PUBLIC	?GUFL_registerLoader@@YAIPAULOADER@@@Z		; GUFL_registerLoader
; Function compile flags: /Ogtpy
;	COMDAT ?GUFL_registerLoader@@YAIPAULOADER@@@Z
_TEXT	SEGMENT
_l$ = 8							; size = 4
?GUFL_registerLoader@@YAIPAULOADER@@@Z PROC		; GUFL_registerLoader, COMDAT

; 20   : 	if(!l->valid) return 0;

	mov	edx, DWORD PTR _l$[esp-4]
	xor	eax, eax
	cmp	BYTE PTR [edx+8], al
	je	SHORT $LN6@GUFL_regis

; 21   : 	for(int i = 0; i < GUFL_MAX_NUMBER_OF_LOADERS; i++)

	mov	ecx, OFFSET _loaderList+8
$LL4@GUFL_regis:

; 22   : 	{
; 23   : 		if(!loaderList[i].valid)

	cmp	BYTE PTR [ecx], 0
	je	SHORT $LN9@GUFL_regis

; 21   : 	for(int i = 0; i < GUFL_MAX_NUMBER_OF_LOADERS; i++)

	add	ecx, 9
	inc	eax
	cmp	ecx, OFFSET _loaderList+152
	jl	SHORT $LL4@GUFL_regis

; 28   : 			return i;
; 29   : 		}
; 30   : 	}
; 31   : 	return 0;

	xor	eax, eax
$LN6@GUFL_regis:

; 32   : }

	ret	0
$LN9@GUFL_regis:

; 24   : 		{
; 25   : 			loaderList[i].valid = true;

	mov	BYTE PTR _loaderList[eax+eax*8+8], 1

; 26   : 			loaderList[i].load = l->load;

	mov	ecx, DWORD PTR [edx]
	mov	DWORD PTR _loaderList[eax+eax*8], ecx

; 27   : 			loaderList[i].verify = l->verify;

	mov	edx, DWORD PTR [edx+4]
	mov	DWORD PTR _loaderList[eax+eax*8+4], edx

; 32   : }

	ret	0
?GUFL_registerLoader@@YAIPAULOADER@@@Z ENDP		; GUFL_registerLoader
_TEXT	ENDS
PUBLIC	?GUFL_getLoader@@YAPAULOADER@@H@Z		; GUFL_getLoader
; Function compile flags: /Ogtpy
;	COMDAT ?GUFL_getLoader@@YAPAULOADER@@H@Z
_TEXT	SEGMENT
_i$ = 8							; size = 4
?GUFL_getLoader@@YAPAULOADER@@H@Z PROC			; GUFL_getLoader, COMDAT

; 35   : 	return &loaderList[i];

	mov	eax, DWORD PTR _i$[esp-4]
	lea	eax, DWORD PTR _loaderList[eax+eax*8]

; 36   : }

	ret	0
?GUFL_getLoader@@YAPAULOADER@@H@Z ENDP			; GUFL_getLoader
_TEXT	ENDS
END
